import os
import boto3
import requests
import anthropic
from datetime import date


def lambda_handler(event, context):
    # --- Load environment variables (set in Lambda console) ---
    ANTHROPIC_API_KEY = os.environ["ANTHROPIC_API_KEY"]
    TAVILY_API_KEY = os.environ["TAVILY_API_KEY"]
    AWS_REGION = os.environ.get("AWS_REGION", "us-east-1")
    EMAIL_FROM = os.environ["EMAIL_FROM"]
    EMAIL_TO = os.environ["EMAIL_TO"]

    today = date.today().strftime("%B %d, %Y")

    # --- Helper: search the web via Tavily ---
    def search_web(query):
        response = requests.post(
            "https://api.tavily.com/search",
            json={
                "api_key": TAVILY_API_KEY,
                "query": query,
                "max_results": 3,
                "days": 1,
            }
        )
        results = response.json()["results"]
        return [{"title": r["title"], "url": r["url"], "content": r["content"][:500]} for r in results]

    # --- Helper: send email via SES ---
    def send_email(subject, html_body):
        ses = boto3.client("ses", region_name=AWS_REGION)
        ses.send_email(
            Source=EMAIL_FROM,
            Destination={"ToAddresses": [EMAIL_TO]},
            Message={
                "Subject": {"Data": subject},
                "Body": {"Html": {"Data": html_body}},
            },
        )
        print(f"Email sent to {EMAIL_TO}")

    # --- Step 1: Run all searches upfront ---
    SEARCHES = {
        "Technology & AI": [
            f"AI artificial intelligence news today {today}",
            f"major tech company news {today}",
            f"emerging technology trends {today}",
        ],
        "World / Geopolitics": [
            f"top world news today {today}",
            f"international geopolitics news {today}",
            f"global conflict diplomacy news {today}",
        ],
        "Business & Markets": [
            f"stock market news today {today}",
            f"economy inflation financial news {today}",
            f"major business earnings corporate news {today}",
        ],
        "Science & Health": [
            f"science discovery research news {today}",
            f"health medicine news today {today}",
        ],
        "US Politics": [
            f"US politics government news today {today}",
            f"congress white house policy news {today}",
        ],
    }

    all_results = {}
    for section, queries in SEARCHES.items():
        section_results = []
        for query in queries:
            print(f"Searching: {query}")
            section_results.extend(search_web(query))
        all_results[section] = section_results

    # --- Step 2: Format results into a prompt for Claude ---
    news_text = ""
    for section, results in all_results.items():
        news_text += f"\n\n## {section}\n"
        for r in results:
            news_text += f"\nTitle: {r['title']}\nURL: {r['url']}\nSummary: {r['content']}\n"

    # --- Step 3: Ask Claude to write the email ---
    claude = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
    print("Sending results to Claude to write the email...")

    response = claude.messages.create(
        model="claude-opus-4-6",
        max_tokens=8096,
        messages=[
            {"role": "user", "content": f"""You are an AI news curator. Today's date is {today}.

Below are news search results organized by section. Using these results, write a complete HTML email digest.

## Curation rules:
- Write a 2-4 sentence factual, neutral summary per story. No opinion, no loaded language.
- Include the source name and a hyperlink.
- If the same story appears from multiple outlets, synthesize into one entry.
- If a story has significant conflicting perspectives across outlets, add a "⚖️ Perspectives vary" note with a one-line summary of each side.
- If a section has no meaningful news, write "No major developments today in this area." instead of padding with stale stories.
- Technology & AI must include at least one AI development story, one major tech company story, and one emerging tech trend.

## HTML email requirements:
- Subject line as an HTML comment at the top: <!-- Subject: 🗞️ Your Morning Briefing — {today} -->
- Header: "Daily Morning Briefing" with today's date
- Subheader: "Your daily AI-curated news digest — balanced, factual, concise."
- Sections in this order: Technology & AI, World / Geopolitics, Business & Markets, Science & Health, US Politics
- Each section with a colored left border accent (Tech=blue, World=green, Business=orange, Science=teal, Politics=purple)
- Max-width 650px centered container, clean sans-serif font, ample whitespace, mobile-friendly
- Headlines bold and slightly larger than body text
- Footer: "Generated by your AI news assistant. Sources are aggregated for balance. Always verify important stories."

Output only the HTML — no extra commentary before or after it.

--- NEWS RESULTS ---
{news_text}"""}
        ]
    )

    # --- Step 4: Send the email ---
    html = response.content[0].text.strip()
    if html.startswith("```"):
        html = html.split("\n", 1)[1]
    if html.endswith("```"):
        html = html.rsplit("```", 1)[0]

    send_email(f"🗞️ Your Morning Briefing — {today}", html)

    return {"statusCode": 200, "body": "Email sent successfully."}
